# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'pfe(b2becb4d-1664-48c3-a742-19c3847899cb)'
    subscriptionId: 'b2becb4d-1664-48c3-a742-19c3847899cb'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'LogicAppDemo'
    location: 'South Central US'
    templateLocation: 'Linked artifact'
    csmFile: 'LogicApp.json'
    csmParametersFile: 'LogicApp-prod.parameters.json'
    deploymentMode: 'Incremental'